[project]
name = "health-records"
description = "Smart contracts for decentralized health record access control"
authors = []
telemetry = true
cache_dir = "./.clarinet"

[contracts.health-records]
path = "contracts/health-records.clar"
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
